apiVersion: nova.openstack.org/v1beta1
kind: Iscsid
metadata:
  name: iscsid-{{ .WorkerOspRole }}
  namespace: openstack
spec:
  iscsidImage: docker.io/tripleotrain/rhel-binary-iscsid:current-tripleo
  roleName: {{ .WorkerOspRole }}