apiVersion: nova.openstack.org/v1beta1
kind: NovaMigrationTarget
metadata:
  name: nova-migration-target-{{ .WorkerOspRole }}
  namespace: openstack
spec:
  novaComputeImage: docker.io/tripleomaster/centos-binary-nova-compute:current-tripleo
  roleName: {{ .WorkerOspRole }}
  sshdPort: {{ .SshdPort }}
